Transcript showCr: (3 < 4) printString.
Transcript showCr: (4 <= 3) printString.
Transcript showCr: ((3 < 4) and: [5 > 2]) printString.
Transcript showCr: ((3 > 4) or: [2 > 5]) printString.
Transcript showCr: (true & false) printString.
Transcript showCr: (false | true) printString.
Transcript showCr: (3 = 3) printString.
Transcript showCr: (3 == 3) printString.
Transcript showCr: 5 even printString.
Transcript showCr: (17 \\ 5) printString.
Transcript showCr: (-17 // 5) printString
