#!/usr/bin/env python3
"""Generate st/ui/gfx/DefaultFont.st — the proportional default strike font,
packed from an X11 BDF bitmap font (UI.md §5.5).

The source is st/ui/gfx/helvR12.bdf (Adobe Helvetica Medium 12, X11 75dpi):
proportional with real upper- and lowercase, distributed under the permissive
Adobe/DEC notice embedded in the BDF file. Glyphs for ASCII 32..126 are packed
side by side into one strike Form of height ascent+descent; per-glyph advances
go into the xTable (count+1 entries: glyph g spans columns xTable[g] up to
xTable[g+1], classic Smalltalk strike layout).

Ink outside a glyph's advance cell (negative BBX offsets / overhang) is
clipped; the script reports how many pixels that drops so a bad font choice is
loud, not silent.

Usage: python3 st/tools/gen_font_bdf.py st/ui/gfx/helvR12.bdf > st/ui/gfx/DefaultFont.st
"""

import sys

FIRST, LAST = 32, 126
COUNT = LAST - FIRST + 1


def parse_bdf(path):
    ascent = descent = None
    glyphs = {}  # code -> (advance, bbx_w, bbx_h, xoff, yoff, [bitmap row ints])
    with open(path) as f:
        lines = iter(f.read().splitlines())
    cur = None
    for line in lines:
        parts = line.split()
        if not parts:
            continue
        if parts[0] == "FONT_ASCENT":
            ascent = int(parts[1])
        elif parts[0] == "FONT_DESCENT":
            descent = int(parts[1])
        elif parts[0] == "STARTCHAR":
            cur = {"code": None}
        elif cur is not None and parts[0] == "ENCODING":
            cur["code"] = int(parts[1])
        elif cur is not None and parts[0] == "DWIDTH":
            cur["advance"] = int(parts[1])
        elif cur is not None and parts[0] == "BBX":
            cur["bbx"] = tuple(int(v) for v in parts[1:5])
        elif cur is not None and parts[0] == "BITMAP":
            cur["rows"] = []
            h = cur["bbx"][1]
            for _ in range(h):
                cur["rows"].append(int(next(lines), 16))
        elif cur is not None and parts[0] == "ENDCHAR":
            code = cur["code"]
            if FIRST <= code <= LAST:
                w, h, xo, yo = cur["bbx"]
                glyphs[code] = (cur["advance"], w, h, xo, yo, cur["rows"])
            cur = None
    return ascent, descent, glyphs


def main():
    path = sys.argv[1]
    ascent, descent, glyphs = parse_bdf(path)
    height = ascent + descent
    space_adv = glyphs[32][0]

    xtable = [0]
    for code in range(FIRST, LAST + 1):
        adv = glyphs[code][0] if code in glyphs else space_adv
        xtable.append(xtable[-1] + adv)
    total = xtable[-1]
    stride = (total + 7) // 8
    bits = bytearray(stride * height)

    clipped = 0
    for i, code in enumerate(range(FIRST, LAST + 1)):
        if code not in glyphs:
            continue
        adv, w, h, xo, yo, rows = glyphs[code]
        top = ascent - h - yo
        row_bytes = (w + 7) // 8
        for r, rowbits in enumerate(rows):
            y = top + r
            rowbits >>= row_bytes * 8 - w  # right-align to w bits
            for c in range(w):
                if not (rowbits >> (w - 1 - c)) & 1:
                    continue
                x = xo + c
                if x < 0 or x >= adv or y < 0 or y >= height:
                    clipped += 1
                    continue
                gx = xtable[i] + x
                bits[y * stride + (gx >> 3)] |= 0x80 >> (gx & 7)
    if clipped:
        print(f"warning: clipped {clipped} ink pixels outside advance cells", file=sys.stderr)

    def wrap(prefix, tokens):
        out, cur = [], "\t^" + prefix
        for tok in tokens:
            if len(cur) + len(tok) + 1 > 90:
                out.append(cur)
                cur = "\t   " + tok
            else:
                cur += ("" if cur.endswith(("[", "(")) else " ") + tok
        return "\n".join(out + [cur])

    print('"GENERATED by st/tools/gen_font_bdf.py from st/ui/gfx/helvR12.bdf — DO')
    print(" NOT EDIT. The default proportional strike font: Adobe Helvetica Medium")
    print(" 12 (X11 75dpi), ASCII 32..126. Copyright 1984-1989, 1994 Adobe Systems")
    print(" Incorporated; Copyright 1988, 1994 Digital Equipment Corporation —")
    print(' distributed under the permissive notice embedded in the BDF file."')
    print()
    print("!StrikeFont class methodsFor: 'default font'!")
    print("defaultHeight")
    print(f"\t^{height}!")
    print("defaultAscent")
    print(f"\t^{ascent}!")
    print("defaultFirst")
    print(f"\t^{FIRST}!")
    print("defaultCount")
    print(f"\t^{COUNT}!")
    print("defaultStrikeWidth")
    print(f"\t^{total}!")
    print("defaultXTable")
    print(wrap("#(", [str(v) for v in xtable]) + ")!")
    print("defaultGlyphBits")
    print(wrap("#[", [str(b) for b in bits]) + "]! !")


if __name__ == "__main__":
    main()
